name: openroadmap
description: Open Source Product Roadmap Planning
publish_to: 'none'

version: 0.1.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 6.0.2
  file_picker: ^4.3.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true

